version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .  
    ports:
      - "8080:8080"  
    environment:
      DATABASE_URL: "postgres://postgres:postgres@0.0.0.0:5432/events_db"
    volumes:
      - ./migrations:/app/migrations  
    depends_on:
      db:
        condition: service_healthy
  
volumes:
  postgres_data:
    driver: local