[workspace]
members = [
    "async_worker",
    "webapp",
    "storage",   
]

[patch.crates-io]
lexical-core = {git = 'https://github.com/Gelbpunkt/rust-lexical', branch = 'fix-warnings-and-update-deps'}